- name: check if nvm is installed
  stat:
    path: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
  register: nvmsh

- name: download nvm installer
  get_url:
    url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh
    dest: /tmp/nvm_install.sh
    mode: 0740
  when: nvmsh.stat.exists == false
  notify: install nvm
